/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/migrate-in-restricted-patient': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['migrateInPatient']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/discharge-to-hospital': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['dischargeToHospital']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/change-supporting-prison': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['changeSupportingPrison']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subject-access-request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
     * @description Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
     */
    get: operations['getSarContentByReference']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/restricted-patient/prison-number/{prison-number}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getRestrictedPatientByPrisonNumber']
    put?: never
    post?: never
    delete: operations['removeRestrictedPatient']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    MigrateInRequest: {
      /**
       * @description Offender number
       * @example A1234AA
       */
      offenderNo: string
      /**
       * @description Hospital location code
       * @example MDI
       */
      hospitalLocationCode: string
    }
    Agency: {
      /**
       * @description Agency id
       * @example MDI
       */
      agencyId: string
      description?: string | null
      longDescription?: string | null
      agencyType?: string | null
      active?: boolean | null
    }
    /** @description Restricted patient */
    RestrictedPatientDto: {
      /**
       * @description Then NOMS Id of the restricted patient
       * @example G1072GT
       */
      prisonerNumber: string
      fromLocation?: components['schemas']['Agency'] | null
      hospitalLocation?: components['schemas']['Agency'] | null
      supportingPrison?: components['schemas']['Agency'] | null
      /**
       * Format: date-time
       * @description Date and time the prisoner was discharged to hospital
       * @example 2021-07-16T12:34:56
       */
      dischargeTime: string
      /** @description Useful comments */
      commentText?: string | null
      /**
       * Format: date-time
       * @description Date time the record was created
       * @example 2020-04-20T17:00:00
       */
      createDateTime?: string | null
      /** @description The user id of the person who created the record */
      createUserId?: string | null
    }
    DischargeToHospitalRequest: {
      /**
       * @description The prisoner number (Nomis ID)
       * @example A1234AA
       */
      offenderNo: string
      commentText?: string | null
      /**
       * @description From location id
       * @example MDI
       */
      fromLocationId: string
      /**
       * @description Hospital location code
       * @example HAZLWD
       */
      hospitalLocationCode: string
      supportingPrisonId?: string | null
      /** Format: date-time */
      dischargeTime?: string | null
    }
    SupportingPrisonRequest: {
      /**
       * @description The prison number
       * @example A1234AA
       */
      offenderNo: string
      /**
       * @description The supporting prison id
       * @example MDI
       */
      supportingPrisonId: string
    }
    Attachment: {
      /**
       * Format: int32
       * @description The number of the attachment which will match any corresponding reference in the content section
       */
      attachmentNumber: number
      /** @description The name or description of the attachment which will be included in the report */
      name: string
      /** @description The content type of the attachment */
      contentType: string
      /** @description The url to be used to download the attachment file */
      url: string
      /**
       * Format: int32
       * @description The size of the attachment file in bytes
       */
      filesize: number
      /** @description The filename of attachment file */
      filename: string
    }
    HmppsSubjectAccessRequestContent: {
      /** @description The content of the subject access request response */
      content: unknown
      /** @description The details of any attachments for the subject access request response */
      attachments?: components['schemas']['Attachment'][] | null
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string | null
      userMessage?: string | null
      developerMessage?: string | null
      moreInfo?: string | null
    }
    DlqMessage: {
      body: {
        [key: string]: unknown
      }
      messageId: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    RestrictedPatient: {
      /**
       * @description The NOMS Id of the restricted patient
       * @example G1072GT
       */
      prisonerNumber: string
      /**
       * @description From location id
       * @example MDI
       */
      fromLocationId: string
      /**
       * @description Hospital location code
       * @example HAZLWD
       */
      hospitalLocationCode: string
      /**
       * @description Supporting prison id
       * @example LEI
       */
      supportingPrisonId: string
      /**
       * Format: date-time
       * @description Date and time the prisoner was discharged to hospital
       */
      dischargeTime: string
      commentText?: string | null
      /** Format: date-time */
      createDateTime?: string | null
      createUserId?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  migrateInPatient: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MigrateInRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RestrictedPatientDto']
        }
      }
    }
  }
  dischargeToHospital: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DischargeToHospitalRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RestrictedPatientDto']
        }
      }
    }
  }
  changeSupportingPrison: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SupportingPrisonRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RestrictedPatientDto']
        }
      }
    }
  }
  getSarContentByReference: {
    parameters: {
      query?: {
        /** @description NOMIS Prison Reference Number */
        prn?: string
        /** @description nDelius Case Reference Number */
        crn?: string
        /** @description Optional parameter denoting minimum date of event occurrence which should be returned in the response */
        fromDate?: string
        /** @description Optional parameter denoting maximum date of event occurrence which should be returned in the response */
        toDate?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Request successfully processed - content found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HmppsSubjectAccessRequestContent']
        }
      }
      /** @description Request successfully processed - no content found */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description Subject Identifier is not recognised by this service */
      209: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description The client does not have authorisation to make this request */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error occurred */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getRestrictedPatientByPrisonNumber: {
    parameters: {
      query?: never
      header?: never
      path: {
        'prison-number': string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RestrictedPatientDto']
        }
      }
    }
  }
  removeRestrictedPatient: {
    parameters: {
      query?: never
      header?: never
      path: {
        'prison-number': string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RestrictedPatient']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
}
