name: Cancel outdated waiting workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "8 4 * * MON-FRI" # Every weekday at 04:08 UTC

jobs:
  cancel-waiting-workflows:
    permissions:
      contents: read
      actions: write
    name: Cancel outdated waiting workflows
    uses: ./.github/workflows/cancel_outdated_workflows_gh_workflow.yml # LOCAL_VERSION
    secrets: inherit
